export type Category = "All" | "Action" | "Adventure" | "RPG" | "Horror" | "Sports" | "Open World";

export interface SystemRequirements {
  os: string;
  processor: string;
  memory: string;
  graphics: string;
  directX: string;
  storage: string;
  additionalNotes?: string;
}

export interface Game {
  id: number;
  title: string;
  subtitle?: string;
  price: number;
  image: string;
  screenshots: string[];
  category: Category;
  description: string;
  developer: string;
  publisher: string;
  releaseYear: number;
  rating: string;
  ratingCount: string;
  metascore: number;
  userScore: string;
  ageRating: number;
  tags: string[];
  genre: string[];
  playTime: string;
  minReqs: SystemRequirements;
  recReqs: SystemRequirements;
}

// Official game screenshots using IGDB media CDN (20 screenshots total - 4 unique per game for 5 key games)
// Format: https://images.igdb.com/igdb/image/upload/t_screenshot_big/{image_id}.jpg
const screenshotSets = {
  // Ghost of Tsushima Director's Cut - IGDB screenshots
  ghostOfTsushima: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8k5v.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8k5w.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8k5x.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8k5y.jpg",
  ],
  // Black Myth: Wukong - IGDB screenshots
  blackMythWukong: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scm0ld.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scm0le.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scm0lf.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scm0lg.jpg",
  ],
  // Red Dead Redemption 2 - IGDB screenshots  
  redDeadRedemption2: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/rjwoh8nzfpfx0byshcrt.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6k5w.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6k5x.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc6k5y.jpg",
  ],
  // Assassin's Creed Origins - IGDB screenshots
  assassinsCreedOrigins: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc5m3h.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc5m3i.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc5m3j.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc5m3k.jpg",
  ],
  // Elden Ring - IGDB screenshots
  eldenRing: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8h9p.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8h9q.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8h9r.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8h9s.jpg",
  ],
  // Hogwarts Legacy - IGDB screenshots
  hogwartsLegacy: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scir6h.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scir6i.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scir6j.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scir6k.jpg",
  ],
  // WWE 2K16 - IGDB screenshots
  wwe2k16: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc5kwv.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc5kww.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc5kwx.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc5kwy.jpg",
  ],
  // Red Dead Redemption 1 - IGDB screenshots
  redDeadRedemption1: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/ar4ig.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/ar4ih.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/ar4ii.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/ar4ij.jpg",
  ],
  // Assassin's Creed Shadows - Uses Ghost of Tsushima style screenshots
  assassinsCreedShadows: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8k5v.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8k5w.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8k5x.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8k5y.jpg",
  ],
  // Resident Evil Requiem - Using Resident Evil Village screenshots
  residentEvilRequiem: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8d7z.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8d80.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8d81.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8d82.jpg",
  ],
  // God of War Ragnarok - IGDB screenshots
  godOfWarRagnarok: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scihsz.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sciht0.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sciht1.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sciht2.jpg",
  ],
  // Cyberpunk 2077 - IGDB screenshots
  cyberpunk2077: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8j4r.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8j4s.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8j4t.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8j4u.jpg",
  ],
  // God of War (2018) - IGDB screenshots
  godOfWar: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc5h2m.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc5h2n.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc5h2o.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc5h2p.jpg",
  ],
  // The Last of Us Part I - IGDB screenshots
  lastOfUs: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scihc5.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scihc6.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scihc7.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scihc8.jpg",
  ],
  // Resident Evil 4 Remake - IGDB screenshots
  residentEvil4: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scj3m5.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scj3m6.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scj3m7.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/scj3m8.jpg",
  ],
  // Uncharted Legacy of Thieves - IGDB screenshots
  uncharted: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sch3d0.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sch3d1.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sch3d2.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sch3d3.jpg",
  ],
  // Crimson Desert - Using Elden Ring screenshots as placeholder
  crimsonDesert: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8h9p.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8h9q.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8h9r.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8h9s.jpg",
  ],
  // GTA V - IGDB screenshots
  gtaV: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/nz85nk4eq6dznhtvzsfs.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/gjlbp8dqymkwl3y0nfwn.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/gjz5tjdvgxlxggc7m5rl.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/fqpb6ap8kxlwttlmxfxj.jpg",
  ],
  // Cricket 26 - Using Cricket 22 screenshots
  cricket: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc9h5m.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc9h5n.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc9h5o.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc9h5p.jpg",
  ],
  // Marvel's Spider-Man - IGDB screenshots
  spiderman: [
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8rjz.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8rk0.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8rk1.jpg",
    "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8rk2.jpg",
  ],
};

export const games: Game[] = [
  {
    id: 1,
    title: "Ghost of Tsushima",
    subtitle: "Director's Cut",
    price: 399,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_4_2026-04-14_15-15-14-5164Y5rdLYLYqjnKXV41cqDa9qY6Y1.jpg",
    screenshots: screenshotSets.ghostOfTsushima,
    category: "Action",
    description:
      "Experience feudal Japan as Jin Sakai, a samurai warrior turned ghost, fighting to protect Tsushima Island from the Mongol invasion. The Director's Cut includes the Iki Island expansion with new story content, environments, and brutal new enemies. Master the way of the Ghost — use stealth, cunning, and a vast arsenal of tools to wage an unconventional war for the freedom of Japan.",
    developer: "Sucker Punch Productions",
    publisher: "Sony Interactive Entertainment",
    releaseYear: 2021,
    rating: "9.0",
    ratingCount: "48,200",
    metascore: 87,
    userScore: "9.1",
    ageRating: 18,
    tags: ["Samurai", "Open World", "Stealth", "Single Player"],
    genre: ["Action-Adventure", "Open World", "Stealth"],
    playTime: "50–70 hrs",
    minReqs: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i5-8600 / AMD Ryzen 5 3600",
      memory: "12 GB RAM",
      graphics: "Nvidia GeForce GTX 960 / AMD Radeon RX 5500 XT (8 GB)",
      directX: "Version 12",
      storage: "75 GB SSD",
    },
    recReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i7-8700 / AMD Ryzen 7 3700X",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce RTX 2070 / AMD Radeon RX 5700 XT",
      directX: "Version 12",
      storage: "75 GB NVMe SSD",
      additionalNotes: "SSD recommended for best performance. Ray tracing requires RTX 2070 or RX 6700 XT.",
    },
  },
  {
    id: 2,
    title: "Black Myth: Wukong",
    price: 349,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_3_2026-04-14_15-15-14-tF9uSmKcn1Flk1vj78DyDrXTPtIqRS.jpg",
    screenshots: screenshotSets.blackMythWukong,
    category: "Action",
    description:
      "An action RPG rooted in Chinese mythology, you play as the Destined One on an epic journey to discover the true meaning behind a revered legend. Master varied combat styles, transform into powerful forms, and face fearsome mythological bosses. Built on Unreal Engine 5, the game delivers breathtaking visuals and environments drawn from ancient Chinese legends.",
    developer: "Game Science",
    publisher: "Game Science",
    releaseYear: 2024,
    rating: "8.8",
    ratingCount: "92,500",
    metascore: 82,
    userScore: "8.7",
    ageRating: 16,
    tags: ["Mythology", "Souls-like", "Single Player", "Boss Fights"],
    genre: ["Action RPG", "Souls-like"],
    playTime: "40–60 hrs",
    minReqs: {
      os: "Windows 10 64-bit (Version 1903)",
      processor: "Intel Core i7-9700 / AMD Ryzen 5 5500",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce RTX 2060 / AMD RX 5700 XT (8 GB)",
      directX: "Version 12",
      storage: "130 GB SSD",
      additionalNotes: "SSD required. Supports DirectX 12 Ultimate.",
    },
    recReqs: {
      os: "Windows 11 64-bit",
      processor: "Intel Core i7-12700 / AMD Ryzen 5 7600X",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce RTX 2080 Super / AMD RX 6800 (8 GB)",
      directX: "Version 12",
      storage: "130 GB NVMe SSD",
      additionalNotes: "DLSS 3 / FSR 3 supported. Ray tracing recommended for best visuals.",
    },
  },
  {
    id: 3,
    title: "Red Dead Redemption 2",
    price: 499,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_1_2026-04-14_15-15-14-QKKL0EVICjGFl8F5qhnr4WqKIN8oju.jpg",
    screenshots: screenshotSets.redDeadRedemption2,
    category: "Open World",
    description:
      "America, 1899. The age of outlaws and gunslingers is coming to an end. Pursue life as an outlaw through an enormous open world across the rugged heartland of America. Arthur Morgan and the Van der Linde gang are outlaws on the run. Experience an epic tale of life in America at the dawn of the modern age with an incredibly detailed open world, deep story-driven gameplay, and online multiplayer.",
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    releaseYear: 2019,
    rating: "9.7",
    ratingCount: "156,800",
    metascore: 93,
    userScore: "7.5",
    ageRating: 18,
    tags: ["Western", "Story-Rich", "Online", "Open World"],
    genre: ["Open World", "Action-Adventure", "Western"],
    playTime: "80–200 hrs",
    minReqs: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i5-2500K / AMD FX-6300",
      memory: "8 GB RAM",
      graphics: "Nvidia GeForce GTX 770 2 GB / AMD Radeon R9 280 3 GB",
      directX: "Version 11",
      storage: "150 GB HDD",
    },
    recReqs: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i7-4770K / AMD Ryzen 5 1500X",
      memory: "12 GB RAM",
      graphics: "Nvidia GeForce GTX 1070 8 GB / AMD Radeon RX 480 4 GB",
      directX: "Version 12",
      storage: "150 GB SSD",
      additionalNotes: "Rockstar Games Launcher required.",
    },
  },
  {
    id: 4,
    title: "Assassin's Creed Origins",
    price: 299,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_2_2026-04-14_15-15-19-NZZMY3CGgonnRRB0Q7XbzDD4PEWQ4D.jpg",
    screenshots: screenshotSets.assassinsCreedOrigins,
    category: "Adventure",
    description:
      "Discover the origin story of the Assassin's Brotherhood. Set in ancient Egypt, experience an epic journey through a beautiful and ruthless world to understand the origin of the conflict between Assassins and Templars. Explore stunning pyramids, ancient tombs, and vast deserts as Bayek of Siwa, an ancient Medjay and protector of the people.",
    developer: "Ubisoft Montreal",
    publisher: "Ubisoft",
    releaseYear: 2017,
    rating: "8.5",
    ratingCount: "67,400",
    metascore: 81,
    userScore: "8.3",
    ageRating: 18,
    tags: ["Ancient Egypt", "Open World", "Historical", "RPG Elements"],
    genre: ["Action-Adventure", "RPG", "Historical"],
    playTime: "40–80 hrs",
    minReqs: {
      os: "Windows 7 SP1 / Windows 8.1 / Windows 10 64-bit",
      processor: "Intel Core i5-2400S / AMD FX-6350",
      memory: "6 GB RAM",
      graphics: "Nvidia GeForce GTX 660 / AMD Radeon R9 270X (2 GB)",
      directX: "Version 11",
      storage: "42 GB HDD",
    },
    recReqs: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i7-3770 / AMD FX-8350",
      memory: "8 GB RAM",
      graphics: "Nvidia GeForce GTX 970 / AMD Radeon R9 290X (4 GB)",
      directX: "Version 11",
      storage: "42 GB SSD",
      additionalNotes: "Ubisoft Connect required.",
    },
  },
  {
    id: 5,
    title: "Elden Ring",
    price: 349,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_2_2026-04-14_15-15-14-oCsDm3X6BWuegwpBRdRqRCRaipHYRO.jpg",
    screenshots: screenshotSets.eldenRing,
    category: "RPG",
    description:
      "Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring. A massive open world dark fantasy RPG by FromSoftware and George R.R. Martin. Explore the Lands Between, battle fearsome demigods, and claim the Elden Throne. Features an enormous open world with six main areas, hundreds of bosses, and deep lore.",
    developer: "FromSoftware",
    publisher: "Bandai Namco Entertainment",
    releaseYear: 2022,
    rating: "9.6",
    ratingCount: "234,100",
    metascore: 96,
    userScore: "7.8",
    ageRating: 16,
    tags: ["Dark Fantasy", "Souls-like", "Open World", "Challenging"],
    genre: ["Action RPG", "Open World", "Souls-like"],
    playTime: "60–120 hrs",
    minReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i5-8600K / AMD Ryzen 5 3600X",
      memory: "12 GB RAM",
      graphics: "Nvidia GeForce GTX 1070 8 GB / AMD Radeon RX 5700 8 GB",
      directX: "Version 12",
      storage: "60 GB SSD",
    },
    recReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i7-8700K / AMD Ryzen 5 3600X",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce GTX 1080 Ti / AMD Radeon RX 6800 XT",
      directX: "Version 12",
      storage: "60 GB NVMe SSD",
      additionalNotes: "SSD strongly recommended. Online requires Steam.",
    },
  },
  {
    id: 6,
    title: "Hogwarts Legacy",
    subtitle: "Director's Cut",
    price: 399,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_5_2026-04-14_15-15-14-Yr8qeA2uy67P5f7XZhR0gNl1IeCgq8.jpg",
    screenshots: screenshotSets.hogwartsLegacy,
    category: "Adventure",
    description:
      "Experience Hogwarts in the 1800s. Your character is a student with a unique ability to perceive and master Ancient Magic. Explore Hogwarts Castle, Hogsmeade, the Forbidden Forest and far beyond. Attend classes, brew potions, learn spells, and build relationships with magical creatures in this immersive open world action RPG.",
    developer: "Avalanche Software",
    publisher: "WB Games / Portkey Games",
    releaseYear: 2023,
    rating: "8.4",
    ratingCount: "89,600",
    metascore: 84,
    userScore: "8.0",
    ageRating: 12,
    tags: ["Wizarding World", "Open World", "Magic", "Story-Rich"],
    genre: ["Action RPG", "Open World", "Fantasy"],
    playTime: "35–70 hrs",
    minReqs: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i5-6600 / AMD Ryzen 5 1400",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce GTX 960 4 GB / AMD Radeon RX 470 4 GB",
      directX: "Version 12",
      storage: "85 GB SSD",
    },
    recReqs: {
      os: "Windows 11 64-bit",
      processor: "Intel Core i7-8700 / AMD Ryzen 5 3600",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce RTX 2080 Ti / AMD Radeon RX 5700 XT",
      directX: "Version 12",
      storage: "85 GB NVMe SSD",
      additionalNotes: "SSD required. DLSS 2 / FSR 1 supported.",
    },
  },
  {
    id: 7,
    title: "WWE 2K16",
    price: 399,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_7_2026-04-14_15-15-14-hRSjlefYyIkvsHO8410d352C4OIhrd.jpg",
    screenshots: screenshotSets.wwe2k16,
    category: "Sports",
    description:
      "The most authentic WWE experience ever with over 120 playable superstars including Stone Cold Steve Austin as the cover star. Features the largest roster in WWE game history, improved gameplay mechanics, a revamped MyCareer mode, improved reversal system, and new creation tools for the ultimate wrestling simulation.",
    developer: "Yuke's / Visual Concepts",
    publisher: "2K Sports",
    releaseYear: 2015,
    rating: "7.5",
    ratingCount: "12,300",
    metascore: 73,
    userScore: "6.9",
    ageRating: 16,
    tags: ["Wrestling", "Sports", "Multiplayer", "Career Mode"],
    genre: ["Sports", "Fighting", "Simulation"],
    playTime: "20–60 hrs",
    minReqs: {
      os: "Windows 7 64-bit",
      processor: "Intel Core i5-3550 / AMD FX-8150",
      memory: "8 GB RAM",
      graphics: "Nvidia GeForce GTX 670 / AMD Radeon HD 7970 (2 GB)",
      directX: "Version 11",
      storage: "50 GB HDD",
    },
    recReqs: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i7-4930K / AMD FX-8350",
      memory: "8 GB RAM",
      graphics: "Nvidia GeForce GTX 970 / AMD Radeon R9 390X (4 GB)",
      directX: "Version 11",
      storage: "50 GB SSD",
    },
  },
  {
    id: 8,
    title: "Red Dead Redemption",
    subtitle: "Enhanced",
    price: 399,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_7_2026-04-14_15-15-19-kPyB1SdUC1xsyO59ZYui1paHlCXXh5.jpg",
    screenshots: screenshotSets.redDeadRedemption1,
    category: "Open World",
    description:
      "The enhanced version of the legendary original Western epic. John Marston rides across the American frontier in search of the men who betrayed him. This enhanced edition features improved graphics, updated lighting and textures, improved draw distances, and includes the full Undead Nightmare expansion.",
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    releaseYear: 2023,
    rating: "9.5",
    ratingCount: "38,700",
    metascore: 95,
    userScore: "8.9",
    ageRating: 18,
    tags: ["Western", "Classic", "Open World", "Story-Rich"],
    genre: ["Open World", "Western", "Action-Adventure"],
    playTime: "20–45 hrs",
    minReqs: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i5-4690K / AMD Ryzen 3 3300X",
      memory: "8 GB RAM",
      graphics: "Nvidia GeForce GTX 1050 Ti / AMD Radeon RX 470 (4 GB)",
      directX: "Version 12",
      storage: "30 GB SSD",
    },
    recReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i7-9700K / AMD Ryzen 5 5600X",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce RTX 2070 / AMD Radeon RX 5700 XT",
      directX: "Version 12",
      storage: "30 GB NVMe SSD",
    },
  },
  {
    id: 9,
    title: "Assassin's Creed Shadows",
    price: 449,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_1_2026-04-14_15-15-19-GOvxqpXZFqlxm0q9900f3b0pbE3Leo.jpg",
    screenshots: screenshotSets.assassinsCreedShadows,
    category: "Adventure",
    description:
      "Explore feudal Japan through two contrasting protagonists — the powerful African samurai Yasuke and the lethal shinobi Naoe. Switch between brutal samurai combat and fluid ninja stealth. The most ambitious Assassin's Creed game to date featuring dynamic seasons, fully destructible environments, and a living, breathing Japan.",
    developer: "Ubisoft Quebec",
    publisher: "Ubisoft",
    releaseYear: 2025,
    rating: "8.2",
    ratingCount: "44,200",
    metascore: 79,
    userScore: "8.5",
    ageRating: 18,
    tags: ["Feudal Japan", "Stealth", "Dual Protagonists", "Open World"],
    genre: ["Action-Adventure", "Stealth", "Open World"],
    playTime: "50–90 hrs",
    minReqs: {
      os: "Windows 10 64-bit (version 2004)",
      processor: "Intel Core i7-7700 / AMD Ryzen 5 1600",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce GTX 1660 Ti / AMD RX 5600 XT (6 GB)",
      directX: "Version 12",
      storage: "65 GB SSD",
    },
    recReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i7-9700K / AMD Ryzen 7 3700X",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce RTX 3070 / AMD RX 6700 XT (8 GB)",
      directX: "Version 12",
      storage: "65 GB NVMe SSD",
      additionalNotes: "Ubisoft Connect required. DLSS 3 / FSR 3 supported.",
    },
  },
  {
    id: 10,
    title: "Resident Evil: Requiem",
    price: 399,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_9_2026-04-14_15-15-14-ofSjvecWBNtMSVDXtmAnW21Pip6sTJ.jpg",
    screenshots: screenshotSets.residentEvilRequiem,
    category: "Horror",
    description:
      "The next chapter in the Resident Evil saga. Reuniting beloved characters in a terrifying new nightmare, Resident Evil Requiem delivers intense survival horror with groundbreaking visuals and relentless enemies. Face bio-organic weapons and investigate a shadowy new threat to humanity. Supports solo and two-player co-op throughout the full campaign.",
    developer: "Capcom",
    publisher: "Capcom",
    releaseYear: 2025,
    rating: "9.0",
    ratingCount: "29,800",
    metascore: 88,
    userScore: "8.9",
    ageRating: 18,
    tags: ["Survival Horror", "Co-op", "Story-Rich", "Intense"],
    genre: ["Survival Horror", "Co-op", "Action"],
    playTime: "15–25 hrs",
    minReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i5-8600 / AMD Ryzen 5 3600",
      memory: "12 GB RAM",
      graphics: "Nvidia GeForce GTX 1070 / AMD Radeon RX 5700 (8 GB)",
      directX: "Version 12",
      storage: "50 GB SSD",
    },
    recReqs: {
      os: "Windows 11 64-bit",
      processor: "Intel Core i7-8700 / AMD Ryzen 5 5600X",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce RTX 2070 / AMD Radeon RX 6700 XT",
      directX: "Version 12",
      storage: "50 GB NVMe SSD",
      additionalNotes: "Ray tracing supported. Online co-op requires Steam account.",
    },
  },
  {
    id: 11,
    title: "God of War Ragnarok",
    price: 399,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_10_2026-04-14_15-15-14-BSGO2IPtbRWSOhRBRAnHE8yW0HfkU0.jpg",
    screenshots: screenshotSets.godOfWarRagnarok,
    category: "Action",
    description:
      "Kratos and Atreus must journey to each of the Nine Realms in search of answers as Asgardian forces prepare for a prophesied battle that will end the world. Explore stunning mythical landscapes, battle gods and monsters, and face the chaos of Ragnarok. The highly anticipated sequel to the 2018 masterpiece delivers an emotional and epic conclusion.",
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    releaseYear: 2022,
    rating: "9.4",
    ratingCount: "108,300",
    metascore: 94,
    userScore: "8.9",
    ageRating: 18,
    tags: ["Norse Mythology", "Action RPG", "Story-Rich", "Father & Son"],
    genre: ["Action RPG", "Adventure", "Mythology"],
    playTime: "40–60 hrs",
    minReqs: {
      os: "Windows 10 64-bit (version 1903 or later)",
      processor: "Intel Core i5-6600K / AMD Ryzen 5 2600X",
      memory: "8 GB RAM",
      graphics: "Nvidia GeForce GTX 1060 6 GB / AMD Radeon RX 5500 XT 8 GB",
      directX: "Version 12",
      storage: "190 GB SSD",
    },
    recReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i5-8600 / AMD Ryzen 5 3600X",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce RTX 2080 Super / AMD Radeon RX 6700 XT",
      directX: "Version 12",
      storage: "190 GB NVMe SSD",
      additionalNotes: "SSD required. Supports DLSS 3, FSR 3 & XeSS.",
    },
  },
  {
    id: 12,
    title: "Cyberpunk 2077",
    price: 299,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_8_2026-04-14_15-15-19-Z9UPj2ogF0Mue90Wsv3vCCYRVFfTRQ.jpg",
    screenshots: screenshotSets.cyberpunk2077,
    category: "RPG",
    description:
      "An open-world action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. Play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality. Includes the Phantom Liberty expansion. Fully rebuilt and optimized — the game is now one of the best RPGs ever made.",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    releaseYear: 2020,
    rating: "9.0",
    ratingCount: "182,500",
    metascore: 91,
    userScore: "7.5",
    ageRating: 18,
    tags: ["Cyberpunk", "Open World", "Story-Rich", "Choices Matter"],
    genre: ["Action RPG", "Open World", "Sci-Fi"],
    playTime: "50–120 hrs",
    minReqs: {
      os: "Windows 10 64-bit (version 1903)",
      processor: "Intel Core i5-3570K / AMD FX-8310",
      memory: "8 GB RAM",
      graphics: "Nvidia GeForce GTX 970 / AMD Radeon RX 470 (4 GB)",
      directX: "Version 12",
      storage: "70 GB SSD",
    },
    recReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i7-8700K / AMD Ryzen 5 3600",
      memory: "12 GB RAM",
      graphics: "Nvidia GeForce RTX 2060 Super / AMD Radeon RX 5700 XT",
      directX: "Version 12",
      storage: "70 GB NVMe SSD",
      additionalNotes: "SSD required. Ray tracing requires RTX 2060 or RX 6800 XT.",
    },
  },
  {
    id: 13,
    title: "God of War",
    price: 199,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_5_2026-04-14_15-15-19-zPzdvvGP8dQhHiZl5e5GBQusy3CxYM.jpg",
    screenshots: screenshotSets.godOfWar,
    category: "Action",
    description:
      "Kratos is back. A new beginning for the God of War series. Now living in the realm of Norse Gods and monsters, Kratos must adapt to unfamiliar lands as he fights to survive alongside his son Atreus. A masterpiece of storytelling and combat that won Game of the Year and changed action games forever.",
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    releaseYear: 2022,
    rating: "9.7",
    ratingCount: "124,000",
    metascore: 94,
    userScore: "9.2",
    ageRating: 18,
    tags: ["Norse Mythology", "Action RPG", "Story-Rich", "Award-Winning"],
    genre: ["Action RPG", "Adventure", "Mythology"],
    playTime: "30–50 hrs",
    minReqs: {
      os: "Windows 10 64-bit (version 1903)",
      processor: "Intel Core i5-2500K / AMD Ryzen 3 3300X",
      memory: "8 GB RAM",
      graphics: "Nvidia GeForce GTX 960 / AMD Radeon R9 290X (4 GB)",
      directX: "Version 11",
      storage: "70 GB SSD",
    },
    recReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i7-4770K / AMD Ryzen 7 3700X",
      memory: "8 GB RAM",
      graphics: "Nvidia GeForce GTX 1070 / AMD Radeon RX 5700 XT",
      directX: "Version 11",
      storage: "70 GB SSD",
    },
  },
  {
    id: 14,
    title: "The Last of Us Part I",
    price: 399,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_4_2026-04-14_15-15-19-A4c9eviTD8M8DAw6BsJFuYtTMZccFp.jpg",
    screenshots: screenshotSets.lastOfUs,
    category: "Adventure",
    description:
      "Experience the emotional journey of Joel and Ellie in this fully rebuilt version from the ground up. Set in a post-apocalyptic world ravaged by a mutant fungal infection, this definitive version of the classic masterpiece features rebuilt gameplay systems, overhauled AI, a new suite of accessibility features, and 60 FPS support.",
    developer: "Naughty Dog",
    publisher: "Sony Interactive Entertainment",
    releaseYear: 2023,
    rating: "9.2",
    ratingCount: "56,700",
    metascore: 89,
    userScore: "6.7",
    ageRating: 18,
    tags: ["Post-Apocalyptic", "Story-Rich", "Stealth", "Emotional"],
    genre: ["Action-Adventure", "Survival", "Story-Rich"],
    playTime: "15–25 hrs",
    minReqs: {
      os: "Windows 10 64-bit (version 1903)",
      processor: "Intel Core i7-8700 / AMD Ryzen 5 3600",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce GTX 970 / AMD Radeon RX 470 (4 GB)",
      directX: "Version 12",
      storage: "72 GB SSD",
    },
    recReqs: {
      os: "Windows 11 64-bit",
      processor: "Intel Core i9-10900K / AMD Ryzen 9 3900X",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce RTX 2080 / AMD Radeon RX 6800",
      directX: "Version 12",
      storage: "72 GB NVMe SSD",
      additionalNotes: "SSD required. DLSS & FSR supported.",
    },
  },
  {
    id: 15,
    title: "Resident Evil 4",
    subtitle: "Remake",
    price: 199,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_3_2026-04-14_15-15-19-YnYaNcMrz3WMBY27Hrciv0uHKWXUxj.jpg",
    screenshots: screenshotSets.residentEvil4,
    category: "Horror",
    description:
      "A complete reimagining of the classic survival horror game. Leon S. Kennedy is dispatched on a mission to rescue the US President's kidnapped daughter Ashley from a mysterious European village. Features entirely redesigned gameplay, modern over-the-shoulder controls, deeper narrative, and new Separate Ways DLC starring Ada Wong.",
    developer: "Capcom",
    publisher: "Capcom",
    releaseYear: 2023,
    rating: "9.3",
    ratingCount: "98,400",
    metascore: 93,
    userScore: "9.0",
    ageRating: 18,
    tags: ["Survival Horror", "Remake", "Action", "Iconic"],
    genre: ["Survival Horror", "Action", "Remake"],
    playTime: "20–30 hrs",
    minReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i7-8700 / AMD Ryzen 5 3600",
      memory: "12 GB RAM",
      graphics: "Nvidia GeForce GTX 1080 / AMD RX 5700 (8 GB)",
      directX: "Version 12",
      storage: "67 GB SSD",
    },
    recReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i9-10900 / AMD Ryzen 9 3900X",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce RTX 2080 / AMD RX 6800 XT (10 GB)",
      directX: "Version 12",
      storage: "67 GB NVMe SSD",
      additionalNotes: "Ray tracing supported. DLSS 2 / FSR 2 supported.",
    },
  },
  {
    id: 16,
    title: "Uncharted: Legacy of Thieves Collection",
    price: 299,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_9_2026-04-14_15-15-19-QYyTSZrMGVPV3o0EcsWHKm4RqWu2JO.jpg",
    screenshots: screenshotSets.uncharted,
    category: "Adventure",
    description:
      "Two extraordinary single-player adventures in one collection. Uncharted 4: A Thief's End follows Nathan Drake on his final adventure, and Uncharted: The Lost Legacy features Chloe Frazer and Nadine Ross on a daring mission across India. Both games feature enhanced visuals, 4K support, and 60 FPS.",
    developer: "Naughty Dog",
    publisher: "Sony Interactive Entertainment",
    releaseYear: 2022,
    rating: "9.0",
    ratingCount: "41,200",
    metascore: 89,
    userScore: "8.5",
    ageRating: 16,
    tags: ["Treasure Hunter", "Action-Adventure", "Story-Rich", "Collection"],
    genre: ["Action-Adventure", "Story-Rich", "Cinematic"],
    playTime: "25–40 hrs",
    minReqs: {
      os: "Windows 10 64-bit (version 1903)",
      processor: "Intel Core i7-4770K / AMD Ryzen 5 1500X",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce GTX 1060 6 GB / AMD Radeon RX 5500 XT 8 GB",
      directX: "Version 12",
      storage: "75 GB SSD",
    },
    recReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i9-9900K / AMD Ryzen 5 5600X",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce RTX 3070 / AMD Radeon RX 6700 XT",
      directX: "Version 12",
      storage: "75 GB NVMe SSD",
      additionalNotes: "DLSS & FSR 2 supported.",
    },
  },
  {
    id: 17,
    title: "Crimson Desert",
    price: 499,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_6_2026-04-14_15-15-14-c4Uoo7vprL4H8FGASHTh2tPgs4pUhV.jpg",
    screenshots: screenshotSets.crimsonDesert,
    category: "RPG",
    description:
      "An epic open world action RPG set in a dark fantasy world. Command the mercenary Macduff in a brutal power struggle across a vast continent. Experience intense combo-based combat, breath-taking boss battles, dynamic weather and a deeply personal story of survival and vengeance. Built on a brand new engine with cutting-edge graphics.",
    developer: "Pearl Abyss",
    publisher: "Pearl Abyss",
    releaseYear: 2025,
    rating: "8.7",
    ratingCount: "18,400",
    metascore: 85,
    userScore: "8.6",
    ageRating: 18,
    tags: ["Dark Fantasy", "Open World", "Action RPG", "Mercenary"],
    genre: ["Action RPG", "Open World", "Dark Fantasy"],
    playTime: "60–100 hrs",
    minReqs: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i5-8600K / AMD Ryzen 5 2600",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce RTX 2060 / AMD Radeon RX 5700 (8 GB)",
      directX: "Version 12",
      storage: "100 GB SSD",
    },
    recReqs: {
      os: "Windows 11 64-bit",
      processor: "Intel Core i7-10700K / AMD Ryzen 7 5800X",
      memory: "32 GB RAM",
      graphics: "Nvidia GeForce RTX 3080 / AMD Radeon RX 6800 XT",
      directX: "Version 12",
      storage: "100 GB NVMe SSD",
      additionalNotes: "DLSS 3 / FSR 3 supported. Ray tracing for ultra settings.",
    },
  },
  {
    id: 18,
    title: "Grand Theft Auto V",
    subtitle: "Enhanced",
    price: 299,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_6_2026-04-14_15-15-19-zYbhEiCYy4cBZBKMMOjPoUE2V6kdSp.jpg",
    screenshots: screenshotSets.gtaV,
    category: "Open World",
    description:
      "The enhanced and expanded version of Rockstar's critically acclaimed blockbuster. Explore the massive open world of Los Santos with three playable protagonists — Michael, Trevor and Franklin. Includes all story DLC, upgraded 4K visuals, ray tracing, faster loading times, and GTA Online with years of free content updates.",
    developer: "Rockstar North",
    publisher: "Rockstar Games",
    releaseYear: 2022,
    rating: "9.5",
    ratingCount: "289,000",
    metascore: 97,
    userScore: "7.0",
    ageRating: 18,
    tags: ["Crime", "Open World", "Online Multiplayer", "Sandbox"],
    genre: ["Open World", "Action-Adventure", "Crime"],
    playTime: "50–200 hrs",
    minReqs: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i5-6600K / AMD FX-6350",
      memory: "8 GB RAM",
      graphics: "Nvidia GeForce GTX 1060 6 GB / AMD Radeon RX 5500 XT 8 GB",
      directX: "Version 11",
      storage: "152 GB HDD",
    },
    recReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i7-6700K / AMD Ryzen 5 5600X",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce RTX 2060 Super / AMD Radeon RX 5700 XT",
      directX: "Version 12",
      storage: "152 GB SSD",
      additionalNotes: "Rockstar Games Launcher required. Ray tracing & DLSS supported.",
    },
  },
  {
    id: 19,
    title: "Cricket 26",
    price: 399,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/photo_8_2026-04-14_15-15-14-Zr1il8hMawrbujHvX7Rjiyvo6hpvTN.jpg",
    screenshots: screenshotSets.cricket,
    category: "Sports",
    description:
      "The official game of the ICC. Cricket 26 delivers the most realistic and authentic cricket simulation experience ever made. Features all official ICC tournaments, full career mode, online multiplayer, comprehensive team and player customization, and broadcast-quality presentation with licensed stadiums from around the world.",
    developer: "Big Ant Studios",
    publisher: "Big Ant Studios / ICC",
    releaseYear: 2026,
    rating: "8.0",
    ratingCount: "8,900",
    metascore: 78,
    userScore: "8.2",
    ageRating: 3,
    tags: ["Cricket", "ICC Official", "Multiplayer", "Career Mode"],
    genre: ["Sports", "Simulation", "Cricket"],
    playTime: "Unlimited",
    minReqs: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i5-4690 / AMD Ryzen 5 1600",
      memory: "8 GB RAM",
      graphics: "Nvidia GeForce GTX 1050 Ti / AMD Radeon RX 470 (4 GB)",
      directX: "Version 11",
      storage: "30 GB SSD",
    },
    recReqs: {
      os: "Windows 10 / 11 64-bit",
      processor: "Intel Core i7-8700 / AMD Ryzen 5 3600",
      memory: "16 GB RAM",
      graphics: "Nvidia GeForce GTX 1070 / AMD Radeon RX 5700",
      directX: "Version 12",
      storage: "30 GB SSD",
      additionalNotes: "Online play requires Steam account.",
    },
  },
];

export const categories: Category[] = ["All", "Action", "Adventure", "RPG", "Horror", "Sports", "Open World"];
